# Generated by Django 5.0.6 on 2024-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                ("surname", models.CharField(verbose_name="Фамилия")),
                (
                    "contact_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/contact_img",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
