# Generated by Django 5.0.6 on 2024-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("description", models.TextField(verbose_name="содержимое")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "public",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="признак публикации"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="slug"
                    ),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите колличество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
