# Generated by Django 5.0.6 on 2024-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_version_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="sign",
            field=models.BooleanField(default=False, verbose_name="активен"),
        ),
    ]
