# Generated by Django 5.0.6 on 2024-06-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_version_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="version",
                to="cars.product",
                verbose_name="Версия машины",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Номер версии"
            ),
        ),
    ]
