# Generated by Django 5.0.6 on 2024-06-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_rename_car_version_vers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="vers",
            new_name="version",
        ),
    ]
