# Generated by Django 5.0.6 on 2024-06-15 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_rename_vers_version_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.TextField(verbose_name="название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.PositiveIntegerField(verbose_name="номер версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="sign",
            field=models.BooleanField(
                default=True, verbose_name="признак текущей версии"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="cars.product",
                verbose_name="Версия машины",
            ),
        ),
    ]
