# Generated by Django 5.0.6 on 2024-06-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_version_name_alter_version_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="номер версии"
            ),
        ),
    ]
