# Generated by Django 5.0.6 on 2024-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_alter_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="номер версии"
            ),
        ),
    ]
