# Generated by Django 5.0.6 on 2024-06-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_alter_version_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="version",
            new_name="product",
        ),
    ]
